name: Sync Repositories

on:
  push:
    branches:
      - master  # Adjust the branch name as needed

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Source Repository
        uses: actions/checkout@v2
        with:
          repository: vemulas19/whatsapp  # Replace with your source repository
          ref: master  # Adjust the branch name as needed

      - name: Push to Target Repository
        run: |
          git remote add target https://github.com/vemulas19/whatsapp-stagging  # Replace with your target repository
          git push target master  # Adjust the branch name as needed
        env:
          GITHUB_TOKEN: ${{ secrets.GH_PAT }}
